---
- hosts: all
  remote_user: vagrant 
  vars:
  - warName: java-example.war
  - warRemotePath: /opt/apache-tomcat-8.5.30/webapps

  tasks:
  - name: Copy WAR to server
    copy: src=target/java-example.war dest={{ warRemotePath }}/{{ warName }} 
    
