---
- hosts: all
  remote_user: vagrant 
  vars:
  - warName: java-example.war  
  - warRemotePath: /var/lib/tomcat7

  tasks:
  - name: Copy WAR to server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} 
    
  - name: kill process is tomcat is still running
    shell: sudo service tomcat7 restart
    
